= Antora Default UI
// Settings:
:experimental:
:hide-uri-scheme:
// Project URLs:
:url-project: https://github.com/codegatecircle/ui-codegate
:url-preview: https://codegatecircle.github.io/ui-codegate
:url-ci-pipelines: {url-project}/pipelines
:img-ci-status: {url-project}/badges/master/pipeline.svg
// External URLs:
:url-antora: https://antora.org
:url-antora-docs: https://docs.antora.org
:url-git: https://git-scm.com
:url-git-dl: {url-git}/downloads
:url-gulp: http://gulpjs.com
:url-nodejs: https://nodejs.org
:url-nvm: https://github.com/creationix/nvm
:url-nvm-install: {url-nvm}#installation

This project is an archetype that demonstrates how to produce a UI bundle that can be used by {url-antora}[Antora] to generated a documentation site.
You can see a preview of the default UI at {url-preview}.

While the default UI is ready to be used with Antora, the intent is that you'll fork it and customize it for your own needs.
It's intentionally minimalistic so as to give you a good starting point without requiring too much effort to customize.

== Command List

[source,text]
----
╰─➤  gulp --tasks
[18:51:10] Build tasks for the Antora default UI project
[18:51:10] ├── default        => bundle
[18:51:10] ├── clean          Clean files and folders generated by build
[18:51:10] ├── format         Format the JavaScript source files using prettify (JavaScript Standard Style)
[18:51:10] ├── build          Build and stage the UI assets for bundling
[18:51:10] ├── bundle         Clean, lint, build, and bundle the UI for publishing
[18:51:10] ├── preview        Generate a preview site and launch a server to view it
[18:51:10] ├── preview:build  Process and stage the UI assets and generate pages for the preview
[18:51:10] └── bundle:pack    Create a bundle of the staged UI assets for publishing
----

== Copyright and License

Copyright (C) 2025 Codegate Circle.

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.

== Authors

Codegate Circle.

== caution

* install `cssnano` and `gulp-cssnano`